---
- name: install
  apt: name=powertop state=latest
  notify: restart-powertop

- name: put tune script
  copy: src=powertop-tune.sh dest=/bin/powertop-tune.sh mode=0755
  notify: restart-powertop

- name: put service
  copy: src=powertop.service dest=/etc/systemd/system/powertop.service
  notify: restart-powertop

- name: start powertop
  service: name=powertop.service state=started enabled=yes
