---
# tasks file for homebrew-packages

- homebrew_tap: tap={{ item }} state=present
  with_items: homebrew_packages_taps

- homebrew: update_homebrew=yes

- homebrew: name={{ item.name }} state={{ item.state|default("latest") }} install_options={{ item.install_options|default() }}
  with_items: homebrew_packages_packages
