---
- name: get latest slack desktop app download url
  shell: |
    wget https://slack.com/downloads/instructions/ubuntu -O - \
      | sed -e 's/"/\n/g' \
      | grep /slack-desktop \
      | grep ".deb"
  register: slack_deb_url

- name: install from specific download site
  apt: deb={{ item }} state=present
  with_items:
    - "https://release.gitkraken.com/linux/gitkraken-amd64.deb"
    - "https://www.rescuetime.com/installers/rescuetime_current_amd64.deb"
    - "{{ slack_deb_url.stdout }}"
