---
- name: remove some packages
  apt: name={{ item }} state=absent
  with_items:
    - plymouth
    - libplymouth4

- name: apt-get update
  apt: update_cache=yes
  check_mode: no
  failed_when: no
  register: res
  changed_when: res.cache_updated != true

- name: apt-get dist-upgrade
  apt: upgrade=dist

- name: add apt-keys
  apt_key: url={{ item }} state=present
  with_items:
    - "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    - "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    - "https://download.docker.com/linux/ubuntu/gpg"
    - "https://apt.enpass.io/keys/enpass-linux.key"
    - "https://packages.microsoft.com/keys/microsoft.asc"

- apt_repository: repo={{ item }} state=present
  with_items:
    - "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} nightly"
    - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    - "deb https://apt.enpass.io/ stable main"
    - "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

- name: apt-get update
  apt: update_cache=yes
  check_mode: no
  failed_when: no
  register: res
  changed_when: res.cache_updated != true

- name: install some packages
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - autoconf
    - build-essential
    - cifs-utils
    - curl
    - code
    - dkms
    - dstat
    - docker-ce
    - emacs
    - enpass
    - exfat-fuse
    - fcitx-skk
    - ffmpeg
    - gimp
    - git
    - git-hub
    - git-core
#    - gnome-shell-extensions
#    - gnome-system-monitor
#    - gnome-tweak-tool
#    - gnome-terminal
    - google-chrome-stable
    - gparted
#    - gtk-theme-switch
    - ibus
    - ibus-skk
    - imagemagick
    - kbuild
    - kernel-package
    - language-pack-gnome-ja
    - language-pack-ja
    - language-selector-gnome
    - libimage-size-perl
    - libjpeg-turbo-progs
    - libmoose-perl
    - libncurses5-dev
    - libpdf-create-perl
    - libqt4-sql-sqlite
    - lm-sensors
    - lsb
    - lynx
    - ncftp
    - ncurses-dev
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - network-manager-vpnc
    - ooo-thumbnailer
    - openjdk-8-doc
    - openjdk-8-jdk
    - openjdk-8-source
    - openssl
    - openvpn
    - optipng
#    - pdftk
    - perltidy
    - php-all-dev
    - php-mbstring
    - php-zip
    - php-curl
    - composer
    - pngnq
    - poppler-data
    - ppa-purge
    - shutter
    - skkdic
    - skkdic-cdb
    - skkdic-extra
    - skksearch
    - sloccount
    - sqlite3
    - ssh
#    - synaptic
    - sysstat
    - ubuntu-fan
    - unpaper
    - usb-creator-gtk
    - vim
    - xbindkeys
    - xclip
    - xvkbd
    - zlib1g
    - zlib1g-dev
    - bridge-utils
    - ruby-all-dev
    - apparmor-utils
    - mysql-workbench
    - virtualbox-5.2
    - chrome-gnome-shell

- name: remove some packages
  apt: name={{ item }} state=absent
  with_items:
    - plymouth
    - libplymouth4

- name: install language-support
  shell: apt-get install -y $(check-language-support)
  register: res
  changed_when: res.rc != 0

# https://booleestreet.net/archives/10321#i-5
- name: put wakenet.sh
  copy: src=wakenet.sh dest=/etc/pm/sleep.d/wakenet.sh mode=0755

- name: put rc.local
  copy: src=rc.local dest=/etc/rc.local
