---
- name: remove some packages
  apt:
    state: absent
    name:
      - plymouth
      - libplymouth5

- name: apt-get update
  apt: update_cache=yes
  check_mode: no
  failed_when: no
  register: res
  changed_when: res.cache_updated != true

- name: apt-get dist-upgrade
  apt: upgrade=dist

- name: Add an apt key by id from a keyserver
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: C99B11DEB97541F0

- name: add apt-keys
  apt_key: url={{ item }} state=present
  with_items:
    - "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    - "https://download.docker.com/linux/ubuntu/gpg"
    - "https://apt.enpass.io/keys/enpass-linux.key"
    - "https://packages.microsoft.com/keys/microsoft.asc"
    - "http://deb.tableplus.com/apt.tableplus.com.gpg.key"
    - "https://workspaces-client-linux-public-key.s3-us-west-2.amazonaws.com/ADB332E7.asc"

- apt_repository: repo={{ item }} state=present
  with_items:
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    - "deb https://apt.enpass.io/ stable main"
    - "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    - "deb [arch=amd64] https://deb.tableplus.com/debian tableplus main"
    - "deb https://cli.github.com/packages stable main"

- name: apt-get update
  apt: update_cache=yes
  check_mode: no
  failed_when: no
  register: res
  changed_when: res.cache_updated != true

- name: install some packages
  apt:
    state: present
    name:
      - apparmor-utils
      - apt-transport-https
      - autoconf
      - bridge-utils
      - build-essential
      - ca-certificates
      - cifs-utils
      - code
      - composer
      - curl
      - default-jdk
      - default-jdk-doc
      - dkms
      - docker.io
      - docker-compose
      - dstat
      - easystroke
      - enpass
      - exfat-fuse
#      - fcitx-skk
      - ffmpeg
      - fish
      - fonts-ricty-diminished
      - gh
      - gimp
      - git
      - git-core
      - gnome-shell-extensions
      - gnome-system-monitor
      - gnome-terminal
      - gnome-tweak-tool
      - golang
      - gparted
      - ibus
      - ibus-skk
      - imagemagick
      - kbuild
      - language-pack-gnome-ja
      - language-pack-ja
      - language-selector-gnome
      - libimage-size-perl
      - libjpeg-turbo-progs
      - libmoose-perl
      - libncurses5-dev
      - libpdf-create-perl
      - libsqlite3-dev
      - lm-sensors
      - lsb
      - lynx
      - ncftp
      - ncurses-dev
      - network-manager-l2tp
      - network-manager-l2tp-gnome
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - network-manager-vpnc
      - network-manager-vpnc-gnome
      - ooo-thumbnailer
      - openssl
      - openvpn
      - optipng
      - pass
      - pdftk
      - peco
      - perltidy
      - pngnq
      - poppler-data
      - ppa-purge
      - qemu-kvm
      - ripgrep
      - ruby-all-dev
      - skkdic
      - skkdic-cdb
      - skkdic-extra
      - sloccount
      - software-properties-common
      - solaar
      - solaar-gnome3
      - sqlite3
      - ssh
      - synaptic
      - sysstat
      - tableplus
      - ubuntu-fan
      - unpaper
      - usb-creator-gtk
      - vagrant
      - variety
      - vim
      - virt-manager
      - virtualbox
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
      - virtualbox-guest-dkms
      - virtualbox-guest-source
      - virtualbox-guest-utils
      - virtualbox-guest-x11
      - xbindkeys
      - xclip
      - xvkbd
      - zlib1g
      - zlib1g-dev

- name: remove some packages
  apt:
    state: absent
    name:
      - plymouth
      - libplymouth5

- name: install language-support
  shell: apt-get install -y $(check-language-support)
  register: res
  changed_when: res.rc != 0

## https://booleestreet.net/archives/10321#i-5
#- name: put wakenet.sh
#  copy: src=wakenet.sh dest=/etc/pm/sleep.d/wakenet.sh mode=0755

- name: put rc.local
  copy: src=rc.local dest=/etc/rc.local

- name: install python pip packages
  shell: pip3 install -U {{ item }}
  with_items:
    - awscli
    - aws-mfa
    - ansible
